var Strings = {
  'nl': { 0:0
  	,'chain2': '2 getallen'
  	,'chain3': '3 getallen'
  	,'chain4': '4 getallen'
    ,'chain5': '5 getallen'
    ,'easy': 'SIMPEL?'
    ,'hard': 'LASTIG!'
    ,'round': 'RONDE'
    ,'unlock': 'Wil je het volledige spel ontgrendelen?'
    ,'Q42': 'FTW!'
    ,'make': 'MAAK EEN &hellip;'
    ,'use': 'en gebruik'
    ,'notyet': 'nog niet!'
    ,'freeplay': 'VRIJ SPEL'
    ,'tiptext1_1': 'TIP<span class="blockstar"></span>SPEEL<br/>VRIJ SPEL<span class="blockstar"></span>'
    ,'tiptext1_2': 'Beweeg de antwoorden boven het bord helemaal naar rechts om te starten.'
    ,'tiptext2_1': 'BEDANKT<span class="blockstar"></span>VEEL PLEZIER<span class="blockstar"></span>'
    ,'tiptext2_2': 'Je hebt nu de volledige versie van Quento!'
    ,'tiptext3_1': 'TIP<span class="blockstar"></span>HAAL MEER UIT QUENTO<span class="blockstar"></span>'
    ,'tiptext3_2': 'Druk op een slot om de volledige versie te kopen met 4 en 5 getallen!'
    ,'tiptext4_1': 'TIP<span class="blockstar"></span>SPEEL WAT JIJ WIL<span class="blockstar"></span>'
    ,'tiptext4_2': 'Druk op een uitkomst boven het bord om die niet te doen.'
    ,'tiptext42_1': '42<span class="blockstar"></span>EEN SPECIAAL GETAL<span class="blockstar"></span>'
    ,'tiptext42_2': 'Waarom? Lees daarvoor het boek "The Hitchhiker\'s Guide to the Galaxy!"'
    ,'skip': 'OVERSLAAN'
    ,'swipe_quento': 'SCHRIJF "QUENTO"'
    ,'getquento': 'download de app voor'
  },
  'en': { 0:0
    ,'chain2': '2 numbers'
    ,'chain3': '3 numbers'
    ,'chain4': '4 numbers'
    ,'chain5': '5 numbers'
    ,'easy': 'EASY?'
    ,'hard': 'HARD!'
    ,'round': 'ROUND'
    ,'unlock': 'Do you want to unlock the full game?'
    ,'Q42': 'FTW!'
    ,'make': 'MAKE A&hellip;'
    ,'use': 'and use'
    ,'notyet': 'not yet!'
    ,'freeplay': 'FREE PLAY'
    ,'tiptext1_1': 'TIP<span class="blockstar"></span>TRY FREE PLAY MODE<span class="blockstar"></span>'
    ,'tiptext1_2': 'Swipe the numbers above the board <br/>all the way to the right.'
    ,'tiptext2_1': 'THANKS<span class="blockstar"></span>HAVE FUN<span class="blockstar"></span>'
    ,'tiptext2_2': 'You have unlocked the full version of Quento. Enjoy!'
    ,'tiptext3_1': 'TIP<span class="blockstar"></span>UNLOCK THE FULL GAME<span class="blockstar"></span>'
    ,'tiptext3_2': 'Tap any lock to buy the full game and play using 4 and 5 numbers!'
    ,'tiptext4_1': 'TIP<span class="blockstar"></span>PLAY WHAT YOU LIKE<span class="blockstar"></span>'
    ,'tiptext4_2': 'Tap a number above the board to disable that challenge.'
    ,'tiptext42_1': '42<span class="blockstar"></span>A SPECIAL NUMBER<span class="blockstar"></span>'
    ,'tiptext42_2': 'Why? Go read the book "The Hitchhiker\'s Guide to the Galaxy" to find out!'
    ,'skip': 'SKIP'
    ,'swipe_quento': 'SWIPE "QUENTO"'
    ,'getquento': 'download the app on'
  }
};